use std::{
    fs,
    path::{Component, Path, PathBuf},
};

use anyhow::{bail, Context, Result};
use clap::ValueEnum;
use kairos_project::{analyze_project, load_project, PackageManifest};

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum TemplateKind {
    Default,
    Briefing,
    Rules,
}

#[derive(Debug, Clone)]
pub struct ScaffoldReport {
    pub root: PathBuf,
    pub package_name: String,
    pub template: TemplateKind,
    pub created: Vec<String>,
    pub skipped: Vec<String>,
    pub notes: Vec<String>,
}

pub fn create_new_project(
    base: &Path,
    name: &str,
    template: TemplateKind,
) -> Result<ScaffoldReport> {
    validate_requested_project_name(name)?;
    let root = base.join(name);
    if root.exists() {
        bail!("target directory `{}` already exists", root.display());
    }

    fs::create_dir_all(&root).with_context(|| format!("failed to create `{}`", root.display()))?;
    scaffold_into(&root, Some(name), template)
}

pub fn init_project(root: &Path, template: TemplateKind) -> Result<ScaffoldReport> {
    if !root.exists() {
        bail!("directory `{}` does not exist", root.display());
    }
    scaffold_into(root, None, template)
}

fn scaffold_into(
    root: &Path,
    requested_name: Option<&str>,
    template: TemplateKind,
) -> Result<ScaffoldReport> {
    let existing_manifest_path = root.join("kairos.toml");
    let mut created = Vec::new();
    let mut skipped = Vec::new();
    let mut notes = Vec::new();

    let package_name = if existing_manifest_path.is_file() {
        let manifest_source = fs::read_to_string(&existing_manifest_path)
            .with_context(|| format!("failed to read `{}`", existing_manifest_path.display()))?;
        let manifest = toml::from_str::<PackageManifest>(&manifest_source)
            .with_context(|| format!("failed to parse `{}`", existing_manifest_path.display()))?;
        skipped.push("kairos.toml".to_string());
        manifest.package.name
    } else {
        let raw_name = requested_name
            .map(|name| {
                Path::new(name)
                    .file_name()
                    .map(|name| name.to_string_lossy().to_string())
                    .unwrap_or_else(|| name.to_string())
            })
            .or_else(|| {
                root.file_name()
                    .map(|name| name.to_string_lossy().to_string())
                    .filter(|name| !name.trim().is_empty())
            })
            .unwrap_or_else(|| "kairos_app".to_string());
        let package_name = sanitize_name(&raw_name);
        if package_name != raw_name {
            notes.push(format!(
                "normalized package name from `{raw_name}` to `{package_name}` for manifest and module paths"
            ));
        }
        let manifest = manifest_source(&package_name);
        write_if_missing(root, &existing_manifest_path, &manifest, &mut created, &mut skipped)?;
        package_name
    };

    for (relative_path, contents) in template_files(template, &package_name) {
        let path = root.join(relative_path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("failed to create `{}`", parent.display()))?;
        }
        write_if_missing(root, &path, &contents, &mut created, &mut skipped)?;
    }

    validate_generated_project(root)?;

    Ok(ScaffoldReport { root: root.to_path_buf(), package_name, template, created, skipped, notes })
}

fn validate_generated_project(root: &Path) -> Result<()> {
    let project = load_project(root).map_err(|error| anyhow::anyhow!(error.to_string()))?;
    analyze_project(&project).map_err(|error| anyhow::anyhow!(error.to_string()))?;
    Ok(())
}

fn write_if_missing(
    root: &Path,
    path: &Path,
    contents: &str,
    created: &mut Vec<String>,
    skipped: &mut Vec<String>,
) -> Result<()> {
    if path.exists() {
        skipped.push(display_relative(root, path));
        return Ok(());
    }

    fs::write(path, contents).with_context(|| format!("failed to write `{}`", path.display()))?;
    created.push(display_relative(root, path));
    Ok(())
}

fn manifest_source(package_name: &str) -> String {
    format!(
        "[package]\nname = \"{package_name}\"\nversion = \"2.0.0\"\nentry = \"src/main.kai\"\n\n[build]\nemit = [\"ast\", \"ir\", \"prompt\"]\n"
    )
}

fn template_files(template: TemplateKind, package_name: &str) -> Vec<(String, String)> {
    let module_name = sanitize_name(package_name);
    let readme = format!(
        "# {package_name}\n\nThis project was generated by Kairos v2.0.\n\nKairos is an AI-first programming language and terminal-native deterministic language platform.\n\n## Quick start\n\n```powershell\ncargo run --bin kairos -- check .\ncargo run --bin kairos -- test .\ncargo run --bin kairos -- doctor .\ncargo run --bin kairos -- shell .\n```\n\n## Project layout\n\n- `kairos.toml`: local project manifest\n- `src/main.kai`: entry module\n- `src/`: deterministic Kairos source tree\n\nTemplate source: `kairos {}`\n",
        match template {
            TemplateKind::Default => "new",
            TemplateKind::Briefing => "new --template briefing",
            TemplateKind::Rules => "new --template rules",
        }
    );

    let mut files = vec![("README.md".to_string(), readme)];
    match template {
        TemplateKind::Default => {
            files.push((
                "src/main.kai".to_string(),
                format!(
                    "module demo.{module_name};\n\ncontext {{\n  goal: \"Start a small Kairos project\";\n  audience: \"LLM\";\n  domain: \"starter\";\n  assumptions: [\n    \"Generated projects should validate immediately.\",\n  ];\n}}\n\nfn main() -> Str\ndescribe \"Return a starter confirmation line\"\ntags [\"starter\", \"default\"]\nrequires []\nensures [len(result) > 0]\n{{\n  return \"Hello from Kairos\";\n}}\n\ntest fn starter_smoke() -> Bool\ndescribe \"Verify the starter entry point stays non-empty\"\ntags [\"test\", \"starter\"]\nrequires []\nensures [result == true]\n{{\n  return len(main()) > 0;\n}}\n"
                ),
            ));
        }
        TemplateKind::Briefing => {
            files.push((
                "src/main.kai".to_string(),
                format!(
                    "module demo.{module_name};\nuse demo.{module_name}.briefing;\n\ncontext {{\n  goal: \"Generate reusable briefing context\";\n  audience: \"LLM\";\n  domain: \"briefing\";\n  assumptions: [\n    \"The shell should support project-aware prompt generation.\",\n  ];\n}}\n\nfn main() -> Str\ndescribe \"Return the starter briefing line\"\ntags [\"starter\", \"briefing\"]\nrequires []\nensures [len(result) > 0]\n{{\n  return briefing_line();\n}}\n\ntest fn briefing_smoke() -> Bool\ndescribe \"Verify that the briefing template returns stable text\"\ntags [\"test\", \"briefing\"]\nrequires []\nensures [result == true]\n{{\n  return len(main()) > 0;\n}}\n"
                ),
            ));
            files.push((
                "src/briefing.kai".to_string(),
                format!(
                    "module demo.{module_name}.briefing;\n\npub fn briefing_line() -> Str\ndescribe \"Return the default briefing line\"\ntags [\"starter\", \"briefing\"]\nrequires []\nensures [len(result) > 0]\n{{\n  return \"Summarize the project before proposing changes.\";\n}}\n"
                ),
            ));
        }
        TemplateKind::Rules => {
            files.push((
                "src/main.kai".to_string(),
                format!(
                    "module demo.{module_name};\nuse demo.{module_name}.rules;\n\ncontext {{\n  goal: \"Run deterministic starter rules\";\n  audience: \"LLM\";\n  domain: \"rules\";\n  assumptions: [\n    \"Generated rules should stay deterministic.\",\n  ];\n}}\n\nfn main() -> Str\ndescribe \"Run the default rules example\"\ntags [\"starter\", \"rules\"]\nrequires []\nensures [len(result) > 0]\n{{\n  return classify(72);\n}}\n\ntest fn rules_smoke() -> Bool\ndescribe \"Verify the starter rules template remains stable\"\ntags [\"test\", \"rules\"]\nrequires []\nensures [result == true]\n{{\n  return classify(72) == \"MEDIUM\";\n}}\n"
                ),
            ));
            files.push((
                "src/rules.kai".to_string(),
                format!(
                    "module demo.{module_name}.rules;\n\npub fn classify(score: Int) -> Str\ndescribe \"Classify a starter score\"\ntags [\"starter\", \"rules\"]\nrequires [score >= 0, score <= 100]\nensures [len(result) > 0]\n{{\n  if score >= 80 {{\n    return \"HIGH\";\n  }} else if score >= 50 {{\n    return \"MEDIUM\";\n  }} else {{\n    return \"LOW\";\n  }}\n}}\n"
                ),
            ));
        }
    }

    files
}

fn validate_requested_project_name(name: &str) -> Result<()> {
    let mut components = Path::new(name).components();
    let Some(component) = components.next() else {
        bail!("project name must not be empty");
    };
    if components.next().is_some() {
        bail!("project name must be a single directory name, not a path");
    }

    let Component::Normal(name) = component else {
        bail!("project name must be a normal directory name");
    };
    let name = name.to_string_lossy();
    if name.trim().is_empty() {
        bail!("project name must not be empty");
    }

    if !name.chars().any(|ch| ch.is_ascii_alphanumeric()) {
        bail!(
            "project name `{name}` must include at least one ASCII letter or digit for manifest/module generation"
        );
    }

    Ok(())
}

fn sanitize_name(value: &str) -> String {
    let mut sanitized = String::new();
    let mut previous_was_separator = false;

    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            sanitized.push(ch.to_ascii_lowercase());
            previous_was_separator = false;
        } else if !previous_was_separator {
            sanitized.push('_');
            previous_was_separator = true;
        }
    }

    let sanitized = sanitized.trim_matches('_').to_string();
    if sanitized.is_empty() {
        "kairos_app".to_string()
    } else {
        sanitized
    }
}

fn display_relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .map(|value| value.to_string_lossy().replace('\\', "/"))
        .unwrap_or_else(|_| path.to_string_lossy().replace('\\', "/"))
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use super::{create_new_project, init_project, TemplateKind};

    #[test]
    fn new_creates_valid_default_project() {
        let tempdir = tempdir().expect("tempdir should exist");
        let report = create_new_project(tempdir.path(), "demo_project", TemplateKind::Default)
            .expect("project should scaffold");

        assert_eq!(report.package_name, "demo_project");
        assert!(report.root.join("kairos.toml").is_file());
        assert!(report.root.join("src/main.kai").is_file());
    }

    #[test]
    fn new_rejects_path_like_names() {
        let tempdir = tempdir().expect("tempdir should exist");
        let error = create_new_project(tempdir.path(), "nested/demo", TemplateKind::Default)
            .expect_err("path-like names should fail");

        assert!(error.to_string().contains("single directory name"));
    }

    #[test]
    fn init_preserves_existing_entry_file() {
        let tempdir = tempdir().expect("tempdir should exist");
        fs::create_dir_all(tempdir.path().join("src")).expect("src should create");
        fs::write(
            tempdir.path().join("src/main.kai"),
            "module demo.keep;\n\nfn main() -> Str\ndescribe \"keep\"\ntags [\"keep\"]\nrequires []\nensures [len(result) > 0]\n{\n  return \"keep\";\n}\n",
        )
        .expect("main should write");

        let report =
            init_project(tempdir.path(), TemplateKind::Default).expect("project should initialize");

        assert!(report.skipped.iter().any(|item| item == "src/main.kai"));
        let contents = fs::read_to_string(tempdir.path().join("src/main.kai"))
            .expect("main should still exist");
        assert!(contents.contains("demo.keep"));
    }

    #[test]
    fn rules_template_creates_multifile_project() {
        let tempdir = tempdir().expect("tempdir should exist");
        let report = create_new_project(tempdir.path(), "rules_demo", TemplateKind::Rules)
            .expect("scaffold");

        assert_eq!(report.template, TemplateKind::Rules);
        assert!(report.root.join("src/rules.kai").is_file());
    }
}
